import Head from 'next/head'
import React from 'react'
import Title from '@components/Title'
import Pill from '@components/Pill'
import ArrowButton from '@components/ArrowButton'

const Home = () => {
  return (
    <div>
      <Head>
        <title>Théo Gândara</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Title text="teste" />
      <Pill text="Front-end developer" />
      <ArrowButton onClick={() => console.log('oi')} />
    </div>
  )
}

export default Home
