import Head from 'next/head'
import React from 'react'
import Title from '../components/Title'

const Home = () => {
  return (
    <div>
      <Head>
        <title>Théo Gândara</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Title text="teste" />
    </div>
  )
}

export default Home
